name: 'Build and Release ccnote on push to release/* branches with tag'

on:
  push:
    branches:
      - 'release/*'
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.11'

    - name: Install dependencies
      run: npm install

    - name: Build for darwin x64
      run: npm run gulp vscode-darwin-x64-min

    - name: Build for darwin arm64
      run: npm run gulp vscode-darwin-arm64-min

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: true

    # - name: Upload Release Asset for darwin x64
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: path/to/your/darwin-x64-binary
    #     asset_name: vscode-darwin-x64
    #     asset_content_type: application/octet-stream

    # - name: Upload Release Asset for darwin arm64
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: path/to/your/darwin-arm64-binary
    #     asset_name: vscode-darwin-arm64
    #     asset_content_type: application/octet-stream
