name: 'Build and Release ccnote on push to release/* branches with tag'

defaults:
  run:
    working-directory: ./repo/ccnote

on:
  push:
    branches:
      - 'release/*'
    tags:
      - '*'

jobs:
  build-and-release-macos-arm64:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        # node-version: '22.11' # tested ok locally
        node-version-file: '.nvmrc'
        cache: 'npm'

    # not sure if required
    - name: Setup Python 3
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: npm install

    # - name: Build for darwin x64
    #   run: npm run gulp vscode-darwin-x64-min

    - name: Build for darwin arm64
      run: npm run gulp vscode-darwin-arm64-min

    - name: Create Release
      id: create_release
      # unmaintained from Mar 4, 2021 - https://github.com/actions/create-release/tree/main?tab=readme-ov-file
      # uses: actions/create-release@v1
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        draft: true
        prerelease: true
        files: ./repo/VSCode-darwin-arm64/Concept-Note.app

    - name: Upload Release Asset for darwin x64
      uses: actions/upload-artifact@v4
      with:
        name: ccnote-darwin-arm64 ${{ github.ref_name }}
        path: ./repo/VSCode-darwin-arm64/Concept-Note.app

    # - name: Upload Release Asset for darwin arm64
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: path/to/your/darwin-arm64-binary
    #     asset_name: vscode-darwin-arm64
    #     asset_content_type: application/octet-stream
