name: 'Build and Release ccnote-insider everyday or manually to the insider repo using nightly branch'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *' # 11pm UTC is 7am UTC+8

jobs:
  build-and-release-macos-arm64:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: nightly
        path: ccnote

    - name: Setup Python 3
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - run: npm install

    - name: Build for darwin arm64
      run: npm run gulp vscode-darwin-arm64-min


    - name: Upload Release Asset for darwin arm64
      uses: actions/upload-artifact@v4
      with:
        name: ccnote-darwin-arm64 ${{ github.sha }}
        path: /Users/runner/work/ccnote/Concept-Note-darwin-arm64/Concept-Note.app

    - name: Zip the app directory
      run: zip -r /Users/runner/work/ccnote/Concept-Note-darwin-arm64.zip /Users/runner/work/ccnote/Concept-Note-darwin-arm64

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        repository: ttdyce/Concept-Note-insider
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref_name }}
        draft: true
        prerelease: true
        files: /Users/runner/work/ccnote/Concept-Note-darwin-arm64.zip

  build-and-release-macos-x64:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: nightly
        path: ccnote

    - name: Setup Python 3
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - run: npm install

    - name: Build for darwin x64
      run: npm run gulp vscode-darwin-x64-min

    - name: Upload Release Asset for darwin x64
      uses: actions/upload-artifact@v4
      with:
        name: ccnote-darwin-x64 ${{ github.sha }}
        path: /Users/runner/work/ccnote/Concept-Note-darwin-x64/Concept-Note.app

    - name: Zip the app directory
      run: zip -r /Users/runner/work/ccnote/Concept-Note-darwin-x64.zip /Users/runner/work/ccnote/Concept-Note-darwin-x64

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        repository: ttdyce/Concept-Note-insider
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: true
        files: /Users/runner/work/ccnote/Concept-Note-darwin-x64.zip
